### ISSUE TITLE
profile page

### ISSUE THREAD

**Issue by kushtra24** [kushtra24/emrabebe-frontend#1]
Te ndertohet nje profile page, ne te cilen mund te qasesh vetem nese je i kyqur, dhe duhet te permbaj keto informacione. 

1. Emri i personit qe eshte kyqur
2. emaili i personit te kyqur
3. data e krijimit te llogaris se personit qe esht ekyqur.

**Comment by kushtra24** [comment]
@ErollMuslija Still not done, you forgot that the circle is not an image but HTML with 2 characters of the name

**Comment by ErollMuslija** [comment]
@kushtra24 Dmth qe ne circle mos mu shvaq nje foto por inicialet e userit i cili eshte i kyqur?
